from importlib import resources
from flask import Flask
from flask_restful import  Api,Resource
import numpy as np
from aco import AntColony
import string

app = Flask(__name__)
api = Api(app)


distances = np.array([[np.inf ,14, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,863, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1855,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[14, np.inf ,654, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,916, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,654, np.inf ,985, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,985, np.inf ,1154, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,1154, np.inf ,379, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,379, np.inf ,2553, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,3529, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,2553, np.inf ,41678, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,41678, np.inf ,19602, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,19602, np.inf ,504, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,504, np.inf ,1999, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1999, np.inf ,1884, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1884, np.inf ,4170, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,4170, np.inf ,615, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,615, np.inf ,652, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,652, np.inf ,50930, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,50930, np.inf ,16407, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,16407, np.inf ,122857, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,122857, np.inf ,441, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,441, np.inf ,86, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,86, np.inf ,852, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,852, np.inf ,4014, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,4014, np.inf ,3431, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,3431, np.inf ,42, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,42, np.inf ,607, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,607, np.inf ,489, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,489, np.inf ,97, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,97, np.inf ,169, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,169, np.inf ,12, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,12, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[863, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,367, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,367, np.inf ,6259, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,6259, np.inf ,7454, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,7454, np.inf ,1517, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1517, np.inf ,73, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,73, np.inf ,359, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,359, np.inf ,1570, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1570, np.inf ,272, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,272, np.inf ,622, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,622, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,3529, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1139, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1139,np.inf ,3146,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,3146,np.inf ,1061,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1061,np.inf ,1436, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1436, np.inf ,730, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,730, np.inf ,733,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,733, np.inf ,49, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,49, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,916, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,385, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,385, np.inf ,80, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,80, np.inf ,5935, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,5935, np.inf ,1417, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1417, np.inf ,3467, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,3467, np.inf ,1414,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,1414, np.inf ,231, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,231, np.inf ,84, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,84, np.inf ,32, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,32, np.inf ,152, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,152, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ],
[1855, np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,9276, np.inf ,np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,9276, np.inf ,723, np.inf ,np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,723, np.inf ,287, np.inf ,np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,287, np.inf ,228, np.inf ],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,228,np.inf ,94],
[np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,np.inf ,94, np.inf ]])

@app.route('/distance/<distan>')
def shortest_path(distan):
    return f'User {distan}'


class Helloworld(Resource):
    def get(self):
        return{"data":"Hello World"}

api.add_resource(Helloworld,"/helloworld");

if __name__ == '__main__':
    app.run(debug = True)


ant_colony = AntColony(distances, 100, 1, 10, 0.95, alpha=1, beta=1)
shortest_path = ant_colony.get_route(start= 0, dest= 28, shaking=False)
print("\nShortest Path :")
print(shortest_path[0])
print("\nDistance :")
print(shortest_path[1])